title: Noura Stories 
author: Nouran Attia 
email: nouranz610@gmail.com 
description: > # A website that has tools that will help you to create books and stories 
  
github_username: Noura16

theme: Jekyll-theme-minimal 
